<?php
namespace Akky\Money;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-16 at 15:30:57.
 */
class ExchangeRateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExchangeRate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExchangeRate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert (1, "USD", "JPY") > 50.
     *
     * @covers ExchangeRate::convert
     */
    public function testConvert()
    {
        $this->assertGreaterThan(
            50,
            $this->object->convert(1, "USD", "JPY")
        );
    }

    /**
     * Generated from @assert (1, "USD", "JPY") < 130.
     *
     * @covers ExchangeRate::convert
     */
    public function testConvert2()
    {
        $this->assertLessThan(
            130,
            $this->object->convert(1, "USD", "JPY")
        );
    }

    /**
     * Generated from @assert ("USD", "JPY") > 50.
     *
     * @covers ExchangeRate::getRate
     */
    public function testGetRate()
    {
        $this->assertGreaterThan(
            50,
            $this->object->getRate("USD", "JPY")
        );
    }

    /**
     * Generated from @assert ("USD", "JPY") < 130.
     *
     * @covers ExchangeRate::getRate
     */
    public function testGetRate2()
    {
        $this->assertLessThan(
            130,
            $this->object->getRate("USD", "JPY")
        );
    }

    /**
     * Generated from @assert ("USD", "JPY") > 50.
     *
     * @covers ExchangeRate::doGetRate
     */
    public function testDoGetRate()
    {
        $this->assertGreaterThan(
            50,
            $this->object->doGetRate("USD", "JPY")
        );
    }

    /**
     * Generated from @assert ("USD", "JPY") < 130.
     *
     * @covers ExchangeRate::doGetRate
     */
    public function testDoGetRate2()
    {
        $this->assertLessThan(
            130,
            $this->object->doGetRate("USD", "JPY")
        );
    }
}
